# Generated by Django 5.1.6 on 2025-02-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='movie/images/default.jpg', upload_to='news/images/'),
        ),
    ]
